// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ShowList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ShowList GetRootAsShowList(ByteBuffer _bb) { return GetRootAsShowList(_bb, new ShowList()); }
  public static ShowList GetRootAsShowList(ByteBuffer _bb, ShowList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ShowList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Show? Shows(int j) { int o = __p.__offset(4); return o != 0 ? (Show?)(new Show()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ShowsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ShowList> CreateShowList(FlatBufferBuilder builder,
      VectorOffset ShowsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ShowList.AddShows(builder, ShowsOffset);
    return ShowList.EndShowList(builder);
  }

  public static void StartShowList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddShows(FlatBufferBuilder builder, VectorOffset ShowsOffset) { builder.AddOffset(0, ShowsOffset.Value, 0); }
  public static VectorOffset CreateShowsVector(FlatBufferBuilder builder, Offset<Show>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateShowsVectorBlock(FlatBufferBuilder builder, Offset<Show>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartShowsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ShowList> EndShowList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ShowList>(o);
  }
};

