// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct UserList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static UserList GetRootAsUserList(ByteBuffer _bb) { return GetRootAsUserList(_bb, new UserList()); }
  public static UserList GetRootAsUserList(ByteBuffer _bb, UserList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UserList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public User? Users(int j) { int o = __p.__offset(4); return o != 0 ? (User?)(new User()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int UsersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<UserList> CreateUserList(FlatBufferBuilder builder,
      VectorOffset UsersOffset = default(VectorOffset)) {
    builder.StartTable(1);
    UserList.AddUsers(builder, UsersOffset);
    return UserList.EndUserList(builder);
  }

  public static void StartUserList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUsers(FlatBufferBuilder builder, VectorOffset UsersOffset) { builder.AddOffset(0, UsersOffset.Value, 0); }
  public static VectorOffset CreateUsersVector(FlatBufferBuilder builder, Offset<User>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateUsersVectorBlock(FlatBufferBuilder builder, Offset<User>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartUsersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<UserList> EndUserList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UserList>(o);
  }
};

